### ISSUE TITLE
Unexpected token ...

### ISSUE THREAD

**Issue by cryptokni8** [netlify/functions#15]
```
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@6.8.0
3 info using node@v8.1.2
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle serverless@1.0.0~prestart: serverless@1.0.0
6 info lifecycle serverless@1.0.0~start: serverless@1.0.0
7 verbose lifecycle serverless@1.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle serverless@1.0.0~start: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/Projects/serverless/node_modules/.bin:/Library/Frameworks/Python.framework/Versions/3.7/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Frameworks/Python.framework/Versions/3.7/bin:~/mongodb-4.0.5/bin:~/mongodb-4.0.5/bin
9 verbose lifecycle serverless@1.0.0~start: CWD: /Users/Projects/serverless
10 silly lifecycle serverless@1.0.0~start: Args: [ '-c', 'netlify-lambda serve lambda' ]
11 silly lifecycle serverless@1.0.0~start: Returned: code: 1  signal: null
12 info lifecycle serverless@1.0.0~start: Failed to exec start script
13 verbose stack Error: serverless@1.0.0 start: `netlify-lambda serve lambda`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at EventEmitter.emit (events.js:213:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:125:13)
```

Sample project to reproduce: https://github.com/cryptokni8/serverless

If i deploy this directly on netlify, the function without any deps works, but the one with deps fails even when i use common js notations

**Comment by cryptokni8** [comment]
```

/Users/Projects/serverless/node_modules/netlify-lambda/lib/config.js:33
    ...buildConfig,
    ^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/Projects/serverless/node_modules/netlify-lambda/lib/build.js:3:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! serverless@1.0.0 start: `netlify-lambda serve lambda`
npm ERR! Exit status 1
npm ERR! 
```

**Comment by Drathal** [comment]
@cryptokni8  try upgrading your node version. Version 6.8 can not handle `Spread Operator` Syntax.

**Comment by tigrankhachikyan** [comment]
I'm getting the same issue when trying to use Parse library. 

```
const Parse = require('parse/node');
```

```
[1] ERROR in ./node_modules/parse/node_modules/ws/lib/stream.js
[1] Module parse failed: Unexpected token (66:4)
[1] You may need an appropriate loader to handle this file type.
[1] |
[1] |   const duplex = new Duplex({
[1] |     ...options,
[1] |     autoDestroy: false,
[1] |     emitClose: false,
[1]  @ ./node_modules/parse/node_modules/ws/index.js 5:34-57
[1]  @ ./node_modules/parse/lib/node/LiveQueryClient.js
[1]  @ ./node_modules/parse/lib/node/Parse.js
[1]  @ ./node_modules/parse/node.js
[1]  @ ./src/lambda/hti.js
```
Node : v13.4.0
Using same environment.

Note rest/spread operators are working in my code, so no idea why webpack complains on it
Any idea?
