### ISSUE TITLE
TLS Error with Interfax via Netlify Functions in Production Only

### ISSUE THREAD

**Issue by preconception** [netlify/functions#40]
Production Error Only

```
Delivery Error { Error: socket hang up
at TLSSocket.onHangUp (_tls_wrap.js:1137:19)
at Object.onceWrapper (events.js:313:30)
at emitNone (events.js:111:20)
at TLSSocket.emit (events.js:208:7)
at endReadableNT (_stream_readable.js:1064:12)
at _combinedTickCallback (internal/process/next_tick.js:138:11)
at process._tickDomainCallback (internal/process/next_tick.js:218:9)
code: ‘ECONNRESET’,
path: null,
host: ‘rest.interfax.net’,
port: 443,
localAddress: undefined }
```

Netlify's Certificate is not working with interfax

I got this message from an interfax employee regarding the issue:

> Hello Sean,
> 
> Based upon the error, it seems to be related to the TLS and the possibly the cipher’s attempting to be used by your application. For a list of cipher’s our endpoint supports, please reference the image below and/or the following link: https://www.ssllabs.com/ssltest/analyze.html?d=rest.interfax.net&latest
> 
> ​
> 
> Thank you,
> 
> Anthony Cox
> Technical Support Engineer, Client Services

**Comment by preconception** [comment]
Sends perfectly fine when using netlify-lambda locally.
